spring.application.name=quiz
server.port=9000

spring.datasource.url=${DB_URL}
spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
jwt.secret=${JWT_SERVICE}

# --- LOGGING CONFIGURATION ---

# 1. Define the logging level
# INFO is standard. DEBUG is for development. ERROR is for failures.
logging.level.root=INFO
logging.level.com.nibin.quiz=DEBUG

# 2. Show SQL queries in logs (Optional, helpful for debugging)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# 3. Save logs to a file (so you can see them later)
logging.file.name=logs/quiz-app.log